In [3]:
import pandas as pd
import pandas as pd
import matplotlib.pyplot as plt

In [4]:
dataset = pd.read_csv('https://raw.githubusercontent.com/mk-gurucharan/Classification/master/IrisDataset.csv')
dataset

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [5]:
dataset.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [6]:
gk = dataset.groupby("species")

In [7]:
gk.first()

            sepal_length  sepal_width  petal_length  petal_width
species
setosa               5.1          3.5           1.4          0.2
versicolor           7.0          3.2           4.7          1.4
virginica            6.3          3.3           6.0          2.5

In [8]:
x = dataset.iloc[:,:4].values
y  = dataset['species'].values

In [9]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest = train_test_split(x,y,test_size = 0.2,random_state = 0)

In [10]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
xtrain = sc.fit_transform(xtrain)
xtest = sc.transform(xtest)

In [11]:
from sklearn.naive_bayes import GaussianNB

classifier = GaussianNB()
classifier.fit(xtrain, ytrain)

GaussianNB()

In [12]:
ypred = classifier.predict(xtest)

In [13]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm=confusion_matrix(ytest,ypred)
print(cm)
print("Accuracy Score :",accuracy_score(ytest,ypred))
df = pd.DataFrame({'real values':ytest,'Predicted Values':ypred})
df

[[11  0  0]
 [ 0 13  0]
 [ 0  1  5]]
Accuracy Score : 0.9666666666666667

   real values Predicted Values
0    virginica        virginica
1   versicolor       versicolor
2       setosa           setosa
3    virginica        virginica
4       setosa           setosa
5    virginica        virginica
6       setosa           setosa
7   versicolor       versicolor
8   versicolor       versicolor
9   versicolor       versicolor
10   virginica       versicolor
11  versicolor       versicolor
12  versicolor       versicolor
13  versicolor       versicolor
14  versicolor       versicolor
15      setosa           setosa
16  versicolor       versicolor
17  versicolor       versicolor
18      setosa           setosa
19      setosa           setosa
20   virginica        virginica
21  versicolor       versicolor
22      setosa           setosa
23      setosa           setosa
24   virginica        virginica
25      setosa           setosa
26      setosa           setosa
27  versicolor       versicolor
28  versicolor       versicolor
29      setosa           setosa